openapi: 3.0.0
info:
  description: |
    This is a sample Petstore server.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0"
  title: E-commerce Project 3
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license: 
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/LukmanNgoding/ecommerce_project3/1.0.0
  - url: 'https://petstore.swagger.io/v2'
tags:
  - name: User #login, register, lihat profile user, update profile user, delelte profile (non aktif dgn delete gorm)
    description: API mengelola fitur User  
  - name: Product
    description:  API mengelola fitur Product  
  - name: Cart
    description:  API mengelola fitur Cart
  - name: Order
    description:  API mengelola fitur Order
  
paths:
  /login:
    post:
      security:
        - bearerAuth: []
      summary: "Login User"
      tags:
      - "User"
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              properties:
                "email":
                  type: string
                "password":
                  type: string
            example:
              email: "adidas@gmail.com"
              password: "123"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccesLoginResult"
              example:
                message: "Login Success"
                data:
                  id: 1
                  username: "adidas"
                  email: "adidas@gmail.com"
                  name: "adidas Feet"
                  phone: "08771079"
                  address: "jl.gunung anthena 1 no 11a, denpasar barat, Bali"
                  shop_name: "Adidas Store"
                  image_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Logo_Adidas.png"
                  token: "bC5jb20ifQ.TKw15NmLbSdIRwXWiu6UiMIudaCe5ecqyANNvA7YL"
        "400" :
          $ref : "#/components/responses/400"  
        '500':
          $ref: "#/components/responses/500"

  /register :
    post:
      summary: "Insert Data User"
      tags:
      - "User"
      requestBody:
        required: true
        content:
          "multipart/form-data":
            schema:
              $ref: "#/components/schemas/InsertUserObject"
            example:
              username: "adidas"
              email: "adidas@gmail.com"
              name: "adidas Feet"
              phone: "08771079"
              address: "jl.gunung anthena 1 no 11a, denpasar barat, Bali"
              shop_name: "Adidas Store"
              file: "9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhQSERUUExQVFRUWGRwaGBgYGB0dGxkcHxccGxocGxoYHCYgGxojHBsdHy8gJCgpLSwsGB4xNTAqNSYrLCkBCQoKDgwOGg8PGiklHx8pLCwpKSkpKSwpLCkpKSwpLCksKSwsLCkpKSkpLCkpKSwpLCwsKSwsLCksKSkpKSksKf/AABEIAJ0BQQMBIgACEQEDEQH/xAAcAAACAwEBAQEAAAAAAAAAAAAEBQIDBgEABwj/xABFEAACAQIEBAQDBgMGAwcFAAABAhEDIQAEEjEFQVFhBhMicTKBkRRCobHB8CNS0QcVM1Ni4RaS8TRygpOiwtIkQ1RVY//EABoBAAIDA."
            encoding:
              file:
                contentType: image/png, image/jpeg       
      responses:
        "201":
          description: "Success create data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "User successfully created"
                data:
                  id: 1
                  username: "adidas"
                  email: "adidas@gmail.com"
                  name: "adidas Feet"
                  phone: "08771079"
                  address: "jl.gunung anthena 1 no 11a, denpasar barat, Bali"
                  shop_name: "Adidas Store"
                  image_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Logo_Adidas.png"
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"
        '500':
          $ref: "#/components/responses/500"
  /users :
    put: 
      security:
        - bearerAuth: []
      summary: "Update Data user"
      tags:
        - "User"
      requestBody:
        description: "Update user data"
        required: true
        content:
          "multipart/form-data":
            schema:
              $ref: "#/components/schemas/InsertUserObject"
            example:
              username: "adidas"
              email: "adidas@gmail.com"
              name: "adidas Feet"
              phone: "08771079"
              address: "jl.gunung anthena 1 no 11a, denpasar barat, Bali"
              shop_name: "Adidas Store"
              file: "9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhQSERUUExQVFRUWGRwaGBgYGB0dGxkcHxccGxocGxoYHCYgGxojHBsdHy8gJCgpLSwsGB4xNTAqNSYrLCkBCQoKDgwOGg8PGiklHx8pLCwpKSkpKSwpLCkpKSwpLCksKSwsLCkpKSkpLCkpKSwpLCwsKSwsLCksKSkpKSksKf/AABEIAJ0BQQMBIgACEQEDEQH/xAAcAAACAwEBAQEAAAAAAAAAAAAEBQIDBgEABwj/xABFEAACAQIEBAQDBgMGAwcFAAABAhEDIQAEEjEFQVFhBhMicTKBkRRCobHB8CNS0QcVM1Ni4RaS8TRygpOiwtIkQ1RVY//EABoBAAIDA."
            encoding:
              file:
                contentType: image/png, image/jpeg     
      responses:
        '200':
          description: "Success update data"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "Success update data"
                data:
                  id: 1
                  username: "adidas"
                  email: "adidas@gmail.com"
                  name: "adidas Feet"
                  phone: "08771079"
                  address: "jl.gunung anthena 1 no 11a, denpasar barat, Bali"
                  shop_name: "Adidas Store"
                  image_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Logo_Adidas.png"
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"           
        '500':
          $ref: "#/components/responses/500"
    delete:
      security:
        - bearerAuth: []
      summary: "Delete User Data"
      tags:
        - "User"
      responses:
        "200":
          description: "Success Delete Data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "Success Delete Data"
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"

  /users/username:
    get: 
      summary: "Profil User"
      tags:
        - "User"
      responses:
        "201":
          description: "Success Profile"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "User successfully Profile"
                data:
                  id: 1
                  username: "adidas"
                  email: "adidas@gmail.com"
                  name: "adidas Feet"
                  phone: "08771079"
                  address: "jl.gunung anthena 1 no 11a, denpasar barat, Bali"
                  shop_name: "Adidas Store"
                  image_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Logo_Adidas.png"
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
  /me:
    get:
      security:
        - bearerAuth: []
      summary: "Get me date User (token)"
      tags:
        - "User"
      responses:
        "201":
          description: "Success User Me"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "User successfully Me"
                data:
                  id: 1
                  username: "adidas"
                  email: "adidas@gmail.com"
                  name: "adidas Feet"
                  phone: "08771079"
                  address: "jl.gunung anthena 1 no 11a, denpasar barat, Bali"
                  shop_name: "Adidas Store"
                  image_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Logo_Adidas.png"
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"

########## PRODUCT ##########

  /products:
    post:
      security:
        - bearerAuth: []
      summary: "Post date Product"
      tags:
        - "Product"
      requestBody:
        description: "Post date Product"
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/PostProductObject"
            example:
              product_name: "Adidas Response Plus"
              price: 2000000
              description: |
                Adidas Response Plus bisa jadi pilihan buat kamu yang senang lari sore di taman sekitar rumah. Menggunakan bahan air mesh, sepatu yang dibanderol dengan harga Rp. 1.599.000 ini mengedepankan fitur sirkulasi udara untuk kaki kamu biar terus terasa nyaman dan nggak gampang berkeringat. Selain itu, outsole-nya menggunakan teknologi Stretchweb yang menyesuaikan pergerakan kaki kamu ketika memijak. 
              stock: 20
              file: "9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhQSERUUExQVFRUWGRwaGBgYGB0dGxkcHxccGxocGxoYHCYgGxojHBsdHy8gJCgpLSwsGB4xNTAqNSYrLCkBCQoKDgwOGg8PGiklHx8pLCwpKSkpKSwpLCkpKSwpLCksKSwsLCkpKSkpLCkpKSwpLCwsKSwsLCksKSkpKSksKf/AABEIAJ0BQQMBIgACEQEDEQH/xAAcAAACAwEBAQEAAAAAAAAAAAAEBQIDBgEABwj/xABFEAACAQIEBAQDBgMGAwcFAAABAhEDIQAEEjEFQVFhBhMicTKBkRRCobHB8CNS0QcVM1Ni4RaS8TRygpOiwtIkQ1RVY//EABoBAAIDA."
            encoding:
              file:
                contentType: image/png, image/jpeg                   
      responses:
        "201":
          description: "Success Post Product"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "Product successfully Post"
                data:
                  id: 1
                  product_name: "Adidas Response Plus"
                  price: 2000000
                  image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/ISzO90zLnp.jpg"
                  description: |
                    Adidas Response Plus bisa jadi pilihan buat kamu yang senang lari sore di taman sekitar rumah. Menggunakan bahan air mesh, sepatu yang dibanderol dengan harga Rp. 1.599.000 ini mengedepankan fitur sirkulasi udara untuk kaki kamu biar terus terasa nyaman dan nggak gampang berkeringat. Selain itu, outsole-nya menggunakan teknologi Stretchweb yang menyesuaikan pergerakan kaki kamu ketika memijak. 
                  stock: 20
                  category: "style"
                  shop_name: "Adidas Shop"
                  id_user_seller: 1
              encoding:
                file:
                  contentType: image/png, image/jpeg  
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
    get:
      summary: "Get All date Product"
      tags:
        - "Product"
      parameters:
        - name: id_user_seller
          in: query
          description: "Id user as seller. Get product that sell by the user. If empty will get from all user."
          required: false 
          schema:
            type: integer
          examples:
            1:
              description: "User with id 1"
              value: 1
            2:
              description: "User with id 2"
              value: 2
        - name: category
          in: query
          description: "Query Get Product using filter by category. If empty will get from all category. Input using lowercase"
          required: false 
          schema:
            type: string
          examples:
            "style":
              description: "Get Product filter by style category."
              value: "style"
            "books":
              description: "Get Product filter by books category."
              value: "style" 
      responses:
        "201":
          description: "Success Get All date Product"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccesArrayResult"
              example:
                message: "Get All Product successfully"
                data:
                - id: 1
                  product_name: "Adidas Response Plus"
                  price: 2000000
                  image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/ISzO90zLnp.jpg"
                  description: |
                    Adidas Response Plus bisa jadi pilihan buat kamu yang senang lari sore di taman sekitar rumah. Menggunakan bahan air mesh, sepatu yang dibanderol dengan harga Rp. 1.599.000 ini mengedepankan fitur sirkulasi udara untuk kaki kamu biar terus terasa nyaman dan nggak gampang berkeringat. Selain itu, outsole-nya menggunakan teknologi Stretchweb yang menyesuaikan pergerakan kaki kamu ketika memijak. 
                  stock: 20
                  category: "style"
                  shop_name: "Adidas Shop"
                  id_user_seller: 1
                - id: 2
                  product_name: "EQT Support ADV"
                  price: 2299000
                  image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/toOfkrbLHI.jpg"
                  description: |
                    EQT Support ADV juga merupakan keluaran seri Originals atau jenis sneakers dari Adidas. Dengan perpaduan bahan mesh dan kulit sintetis, sepatu ini memberikan aksen kalem dan sporty, serta rasa nyaman bagi pemakainya. Sepatu yang memiliki nilai seharga Rp. 2.299.000 ini hadir dengan desain yang unik, sehingga memberi kesan spesial bagi sang pemakai. 
                  stock: 20
                  category: "style"
                  shop_name: "Adidas Shop"
                  id_user_seller: 1

              encoding:
                file:
                  contentType: image/png, image/jpeg 
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
  /products/{id}:
    get:
      summary: "Get data by id product"
      tags:
        - "Product"
      parameters:
      - name : id
        in : path
        description: "Id Product to get data"
        required: true
        schema :
          type: integer
        examples:
          1 :
            description: "Id product 1 "
            value : 1
      responses:
        "200":
          description: "Success Update Product"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "Product successfully Post"
                data:
                  id: 1
                  product_name: "Adidas Response Plus"
                  price: 2000000
                  image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/ISzO90zLnp.jpg"
                  description: |
                    Adidas Response Plus bisa jadi pilihan buat kamu yang senang lari sore di taman sekitar rumah. Menggunakan bahan air mesh, sepatu yang dibanderol dengan harga Rp. 1.599.000 ini mengedepankan fitur sirkulasi udara untuk kaki kamu biar terus terasa nyaman dan nggak gampang berkeringat. Selain itu, outsole-nya menggunakan teknologi Stretchweb yang menyesuaikan pergerakan kaki kamu ketika memijak. 
                  stock: 20
                  category: "style"
                  shop_name: "Adidas Shop"
                  id_user_seller: 1
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
    put:
      security:
        - bearerAuth: []
      summary: "Update date Product"
      tags:
        - "Product"
      parameters:
      - name : id
        in : path
        description: "Id Product to update data"
        required: true
        schema :
          type: integer
        examples:
          1 :
            description: "Id product 1 "
            value : 1
      requestBody:
        description: "Update date Product"
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/PostProductObject"
            example:
              data:
                product_name: "Adidas Response Plus"
                price: 2000000
                description: |
                  Adidas Response Plus bisa jadi pilihan buat kamu yang senang lari sore di taman sekitar rumah. Menggunakan bahan air mesh, sepatu yang dibanderol dengan harga Rp. 1.599.000 ini mengedepankan fitur sirkulasi udara untuk kaki kamu biar terus terasa nyaman dan nggak gampang berkeringat. Selain itu, outsole-nya menggunakan teknologi Stretchweb yang menyesuaikan pergerakan kaki kamu ketika memijak. 
                stock: 20
                file: "9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhQSERUUExQVFRUWGRwaGBgYGB0dGxkcHxccGxocGxoYHCYgGxojHBsdHy8gJCgpLSwsGB4xNTAqNSYrLCkBCQoKDgwOGg8PGiklHx8pLCwpKSkpKSwpLCkpKSwpLCksKSwsLCkpKSkpLCkpKSwpLCwsKSwsLCksKSkpKSksKf/AABEIAJ0BQQMBIgACEQEDEQH/xAAcAAACAwEBAQEAAAAAAAAAAAAEBQIDBgEABwj/xABFEAACAQIEBAQDBgMGAwcFAAABAhEDIQAEEjEFQVFhBhMicTKBkRRCobHB8CNS0QcVM1Ni4RaS8TRygpOiwtIkQ1RVY//EABoBAAIDA."
            encoding:
              file:
                contentType: image/png, image/jpeg   
      responses:
        "200":
          description: "Success Update Product"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "Product successfully Post"
                data:
                  id: 1
                  product_name: "Adidas Response Plus"
                  price: 2000000
                  image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/ISzO90zLnp.jpg"
                  description: |
                    Adidas Response Plus bisa jadi pilihan buat kamu yang senang lari sore di taman sekitar rumah. Menggunakan bahan air mesh, sepatu yang dibanderol dengan harga Rp. 1.599.000 ini mengedepankan fitur sirkulasi udara untuk kaki kamu biar terus terasa nyaman dan nggak gampang berkeringat. Selain itu, outsole-nya menggunakan teknologi Stretchweb yang menyesuaikan pergerakan kaki kamu ketika memijak. 
                  stock: 20
                  category: "style"
                  shop_name: "Adidas Shop"
                  id_user_seller: 1
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
    delete:
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: "ID Product parameter"
          required: true
          schema:
            type: integer
      summary: "Delete Product data"
      tags:
        - "Product"
      responses:
        "200":
          description: "Success Delete Product Data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "Success Delete Product Data"
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"

########## CART ########
  /carts:
    post:
      security:
        - bearerAuth: []
      summary: "Post data Cart"
      tags:
        - "Cart"
      requestBody:
        description: "Post data Cart"
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/PostCartObject"
            example:
              data:
                product_name: "Adidas Response Plus"
                price: 2000000
                qty: 1
                sub_total: 2000000
                image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/ISzO90zLnp.jpg"
                notes: |
                  Warna Biru
                category: "style"
                shop_name: "Adidas Shop"
                id_product: 1
                id_user_seller: 1
      responses:
        "201":
          description: "Success Post data Cart"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccesArrayResult"
              example:
                message: "Post Cart successfully"
                data:
                - id: 1
                  product_name: "Adidas Response Plus"
                  price: 2000000
                  qty: 1
                  sub_total: 2000000
                  image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/ISzO90zLnp.jpg"
                  notes: |
                    Warna Biru
                  category: "style"
                  shop_name: "Adidas Shop"
                  id_product: 1
                  id_user_seller: 1
                  id_user_buyer: 2
                - id: 2
                  product_name: "EQT Support ADV"
                  price: 2299000
                  qty: 1
                  sub_total: 2299000                
                  image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/toOfkrbLHI.jpg"
                  notes: ""
                  stock: 20
                  category: "style"
                  shop_name: "Adidas Shop"
                  id_product: 2
                  id_user_seller: 1
                  id_user_buyer: 2
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
  /mycarts:
    get:
      security:
        - bearerAuth: []
      summary: "Get all user cart data by user token"
      tags:
        - "Cart"
      responses:
        "200":
          description: "Success Get user cart data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccesArrayResult"
              example:
                message: "Get Cart successfully"
                data:
                - id_user_seller: 1
                  shop_name: "Adidas Shop"
                  items:
                  - id: 1
                    product_name: "Adidas Response Plus"
                    price: 2000000
                    qty: 1
                    sub_total: 2000000
                    image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/ISzO90zLnp.jpg"
                    notes: |
                      Warna Biru
                    category: "style"
                    shop_name: "Adidas Shop"
                    id_product: 1
                    id_user_seller: 1
                    id_user_buyer: 2   
                  - id: 2
                    product_name: "EQT Support ADV"
                    price: 2299000
                    qty: 1
                    sub_total: 2299000                
                    image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/toOfkrbLHI.jpg"
                    notes: ""
                    stock: 20
                    category: "style"
                    shop_name: "Adidas Shop"
                    id_product: 2
                    id_user_seller: 1
                    id_user_buyer: 2          
                - id_user_seller: 2
                  shop_name: "Mangga Dua Computer Shop"
                  items:
                  - id: 3
                    product_name: "KLEVV SO-DIMM DDR4 Value Series PC25600 3200MHZ 8GB"
                    price: 380000
                    qty: 1
                    sub_total: 380000
                    image_url: "https://images.tokopedia.net/img/cache/900/VqbcmM/2022/8/16/ceeb8319-5231-4e5b-bdc9-335330bd0078.jpg"
                    notes: ""
                    category: "tech"
                    shop_name: "Mangga Dua Computer Shop"
                    id_product: 3
                    id_user_seller: 3
                    id_user_buyer: 2   
                  - id: 4
                    product_name: "GALAX SONAR-04 Wired Gaming Headset - USB 7.1 Channel RGB"
                    price: 495000
                    qty: 1
                    sub_total: 495000                
                    image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/toOfkrbLHI.jpghttps://ecs7.tokopedia.net/img/cache/700/VqbcmM/2022/2/14/858492fc-5b10-4eb1-8782-fa28cb61911a.jpg"
                    notes: ""
                    stock: 20
                    category: "tech"
                    shop_name: "Mangga Dua Computer Shop"
                    id_product: 4
                    id_user_seller: 3
                    id_user_buyer: 2          
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
  /carts/{id}:
    get:
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: "ID_cart parameter"
          required: true
          schema:
            type: integer
      summary: "Get data Cart"
      tags:
        - "Cart"
      responses:
        "201":
          description: "Success Get date Cart"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccesArrayResult"
              example:
                message: "Get Cart successfully"
                data:
                  id: 1
                  product_name: "Adidas Response Plus"
                  price: 2000000
                  qty: 1
                  sub_total: 2000000
                  image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/ISzO90zLnp.jpg"
                  notes: |
                    Warna Biru
                  category: "style"
                  shop_name: "Adidas Shop"
                  id_product: 1
                  id_user_seller: 1
                  id_user_buyer: 2
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
    put:
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: "ID cart detail parameter"
          required: true
          schema:
            type: integer
      summary: "Update data Cart detail"
      tags:
        - "Cart"
      requestBody:
        description: "Update data Cart"
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/PostCartObject"
            example:
              data:
                id: 1
                qty: 1
                sub_total: 2000000
                notes: |
                  Warna Biru
      responses:
        "201":
          description: "Success update Cart detail"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccesArrayResult"
              example:
                message: "Update Cart detail successfully"
                data:
                  id: 1
                  product_name: "Adidas Response Plus"
                  price: 2000000
                  qty: 1
                  sub_total: 2000000
                  image_url: "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/ISzO90zLnp.jpg"
                  notes: |
                    Warna Biru
                  category: "style"
                  shop_name: "Adidas Shop"
                  id_product: 1
                  id_user_seller: 1
                  id_user_buyer: 1
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
    delete:
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: "ID cart parameter"
          required: true
          schema:
            type: integer
      summary: "Delete cart data"
      tags:
        - "Cart"
      responses:
        "200":
          description: "Success Delete cart Data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResult"
              example:
                message: "Success Delete cart Data"
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"

  ######### ORDER #########

  /order/:
    post:
      security:
        - bearerAuth: []
      summary: "Insert new order"
      tags:
        - "Cart"
      requestBody:
          description: "Post data Order"
          required: true
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/PostOrdertObject"
              example:
                data:
                  id_user_seller: 3
                  shipping_name: "luky"
                  shipping_address: "Jakarta"
                  shipping_phone: 088280020
                  shop_name: "kuda laut"
                  gross_ammount: 3
                  order_status: true
      responses:
        "201":
          description: "Success Post date Order"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccesArrayResult"
              example:
                message: "Post date Order successfully"
                data:
                  id_order: 1
                  id_user_buyer: 2
                  id_user_seller: 3
                  shipping_name: "luky"
                  shipping_address: "Jakarta"
                  shipping_phone: 088280020
                  shop_name: "kuda laut"
                  gross_ammount: 3
                  order_status: true
                  snap_token: "jsjallslasjlasyisbdmdamdh"
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"

  /orders/{id}:
    get:
      security:
        - bearerAuth: []
      parameters:
        - name: id_order
          in: path
          required: true
          schema:
            type: integer
      summary: "Get data Order"
      tags:
        - "Order"
      responses:
        "201":
          description: "Success Get date Order"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccesArrayResult"
              example:
                message: "Get date Order successfully"
                data:
                  id_order: 1
                  id_user_buyer: 2
                  id_user_seller: 3
                  shipping_name: "luky"
                  shipping_address: "Jakarta"
                  shipping_phone: 088280020
                  shop_name: "kuda laut"
                  gross_ammount: 3
                  order_status: true
        "400" :
          $ref : "#/components/responses/400"
        "401" :
          $ref : "#/components/responses/401"   
        '500':
          $ref: "#/components/responses/500"
components:
  securitySchemes:
    "bearerAuth" :
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    "GetUserObject":
      type: object
      properties:
        "id":
          type: integer
        "username":
          type: string
        "email":
          type: string
        "password":
          type: string
        "name":
          type: string
        "phone":
          type: string
        "address":
          type: string    
        "shop_name":
          type: string  
        "image_url":
          type: string  
    "ArrayUserObj":
      type: array
      items :
        $ref: "#/components/schemas/GetUserObject"
    "InsertUserObject":
      type: object
      properties:
        "username":
          type: string
        "email":
          type: string
        "password":
          type: string
        "name":
          type: string
        "phone":
          type: string
        "address":
          type: string    
        "shop_name":
          type: string    
        "file":
          type: string    
          format: binary   
    "EditUserObject":
      type: object
      properties:
        "id":
          type: integer
        "username":
          type: string
        "email":
          type: string
        "password":
          type: string
        "name":
          type: string
        "phone":
          type: string
        "address":
          type: string    
        "shop_name":
          type: string    
        "file":
          type: string    
          format: binary  
    "PostProductObject":
      type: object
      properties:
        "id":
          type: integer
        "product_name":
          type: string
        "price":
          type: integer
        "image_url":
          type: string
        "description":
          type: string
        "shop_name":
          type: string
        "is_sold":
          type: string
        "id_user_seller":
          type: string
    "PostCartObject":
      type: object
      properties:
        "id":
          type: integer
        "product_name":
          type: string
        "price":
          type: integer
        "qty":
          type: integer
        "sub_total":
          type: integer
        "image_url":
          type: string
        "notes":
          type: string
        "shop_name":
          type: string
        "id_user_seller":
          type: string
    "PostCheckoutObject":
      type: object
      properties:
        "id":
          type: integer
        "product_name":
          type: string
        "price":
          type: integer
        "qty":
          type: integer
        "sub_total":
          type: string
        "image_url":
          type: string
        "notes":
          type: string
        "shop_name":
          type: string
        "id_user_seller":
          type: string
    "PostOrdertObject":
      type: object
      properties:
        "id_checkout ":
          type: integer
        "sub_total":
          type: string
        "shipping_name":
          type: string
        "shipping_cost":
          type: integer
        "gross_ammount":
          type: integer
    "CommentObject":
      type: object
      properties:
        "id":
          type: integer
        "name":
          type: integer
        "comment_value":
          type: string
        "id_user":
          type: integer
        "id_posting":
          type: string
    "InsertCommentObject":
      type: object
      properties:
        "name":
          type: string
        "comment_value":
          type: string
        "id_user":
          type: integer
        "id_posting":
          type: string  
    "EditCommentObject":
      type: object
      properties:
        "comment_value":
          type: string    
    "ArrCommentObject":
      type: array
      items:
        $ref: "#/components/schemas/CommentObject"    
    "SuccessResult":
      type: object
      properties:
        message: 
          type: string
        data:
          type: object
    "SuccesLoginResult":
      type: object
      properties:
        message: 
          type: string
        data:
          type: object
        token: 
          type: string
    "SuccesArrayResult":
      type: object
      properties:
        message: 
          type: string
        data:
          type: array
          items : 
            $ref: "#/components/schemas/ArrCommentObject"
          
  responses:
    '200':
      description: "Success Process Data"
      content:
        application/json:
          schema:
            type: object
            properties:
              message: 
                type: string
              data:
                type: object
    '201':
      description: "Success Create Data"
      content:
        application/json:
          schema:
            type: object
            properties:
              message: 
                type: string
              data:
                type: object
    '400':
      description: "Wrong Request From User"
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: "Process Failed. Please check your input."
    '401':
      description: "Authorization information is missing or invalid."
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: "Process Failed. User not authorized for this request."
    '500':
      description: "Error from server"
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: "Process Failed. Please check server."